### ISSUE TITLE
Principios SOLID

### ISSUE THREAD

**Issue by edwin06111998** [NemesLaszlo/Simple_ATMSimulator#1]
Hello, my name is Edwin Veloz, I am taking a software design class, and I have a duty to choose a public repository and correct it so that it does not violate SOLID principles. Together with my group, we have chosen your repository and modified it to comply with the SOLID principles. We found that your repository violated the first two principles. The new repository link already modified: https://github.com/Joan-Gutierrez11/SOLID-Repositorio/tree/master/ATMSimulator-SOLID.

**Comment by NemesLaszlo** [comment]
Hello, its sounds really good, and i really appreciate that you and your group picked one of my repository. Yes, it is older one, feel free to create a pull request if you would like to, and i will merge the pull request with the original project.
